name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # This workflow will be triggered when changes are pushed to the 'main' branch
  pull_request:
    branches:
      - main  # It will also be triggered when a pull request is opened targeting the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment for the job

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout the repository
      uses: actions/checkout@v2  # This step checks out the code in the current repository

    # Step 2: Set up Docker Buildx (for advanced image building)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # This sets up Docker Buildx to allow multi-platform builds

    # Step 3: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Log into Docker Hub using GitHub Secrets
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password or access token from GitHub Secrets

    # Step 4: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-repo:latest .  # Build the Docker image with a tag

    # Step 5: Push the Docker image to Docker Hub
    - name: Push the Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-repo:latest  # Push the built image to Docker Hub

    # Step 6: Log out from Docker Hub after pushing the image
    - name: Logout from Docker Hub
      run: docker logout  # Log out from Docker Hub after the image is pushed
